name: Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  # Tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3
  #     - name: install node modules
  #       run: npm ci
  #     - name: run tests
  #       run: npm test
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: create SSH key
        run: echo "${{ secrets.LINODE_SSH_KEY }}" > key.ppk
      - name: login to linode
        run: ssh ${{ secrets.SERVER_URL }} matt
      - name: kill existing process
        run: pkill node start.js
      - name: clone repo
        run: cd ../../srv/workster/Workster-Server/ && git pull https://github.com/MattV-NL/Workster-Server.git
      - name: install node modules
        run: npm i
      - name: start server
        run: cd /src && node start.js
